// UI strings. Every key must exist in both languages (checked by dict.test.ts).

export const en = {
  "app.name": "Lanscape",
  "nav.network": "Network",
  "nav.map": "Map",
  "nav.devices": "Devices",
  "nav.runs": "Runs",
  "nav.settings": "Settings",
  "nav.account": "Account",
  "nav.logout": "Log out",
  "theme.toggle": "Toggle theme",
  "lang.toggle": "Русский",

  "login.title": "Sign in",
  "login.username": "Username",
  "login.password": "Password",
  "login.code": "Two-factor code",
  "login.submit": "Sign in",
  "setup.title": "Create the administrator",
  "setup.hint": "No users exist yet. The first account becomes an administrator.",
  "setup.submit": "Create and sign in",
  "setup.password_hint": "At least 10 characters",

  "net.check_all": "Check all",
  "net.reachability": "Reachability only",
  "net.aggregate": "Aggregate",
  "net.cancel": "Cancel",
  "net.options": "Options",
  "net.udp": "UDP test",
  "net.bidir": "Bidirectional",
  "net.duration": "Duration, s",
  "net.streams": "Streams",
  "net.estimate": "{paths} paths, about {time}",
  "net.running": "Running: {done} of {total}, ~{eta} left",
  "net.last_run": "Last run #{id}, {when}",
  "net.no_run": "No runs yet. Press “Check all”.",
  "net.no_agents": "Connect at least two agents that share a network (Settings → Agents).",
  "net.problems": "Problems",
  "net.no_problems": "No problems found.",
  "net.matrix": "Speed matrix",
  "net.from_to": "from \\ to",
  "net.expected": "expected {v}",
  "net.unknown": "unknown",
  "net.anomalies": "Anomalies",
  "net.aggregate_result": "Aggregate capacity",
  "net.total": "total",

  "verdict.green": "≥ 85% of expected",
  "verdict.yellow": "50–85% of expected",
  "verdict.red": "< 50% or error",
  "verdict.purple": "limited by agent CPU",
  "verdict.none": "no expected speed / no data",

  "problem.tcp_intercepted": "TCP intercepted while ICMP ok",
  "problem.mtu": "MTU problem",
  "problem.slow": "Speed below expected",
  "problem.path_mismatch": "Path does not match",
  "problem.unreachable": "Unreachable",
  "problem.macvlan": "macvlan parent cannot reach child",
  "problem.loss": "Packet loss",
  "problem.cpu_bound": "Limited by CPU",
  "problem.rtt": "High latency",
  "hint.tcp_intercepted":
    "A transparent proxy (TPROXY/REDIRECT) or a firewall captures TCP in this subnet. Exclude the subnet from interception.",
  "hint.mtu": "A link on this path has a smaller MTU. Align the MTU on all hops or lower it on the endpoints.",
  "hint.slow": "Check link negotiation, cabling and the uplinks between switches.",
  "hint.path_mismatch": "Traffic left through another interface. Check routes, ip rule and rp_filter.",
  "hint.unreachable": "Check VLAN tagging, the firewall and that the agent listens on port 47700.",
  "hint.macvlan":
    "Create a macvlan sibling on the host (ip link add storage0 link <parent> type macvlan mode bridge) and move the host address there.",
  "hint.loss": "Check cabling, duplex and interface errors.",
  "hint.cpu_bound": "The agent CPU was saturated; the link may be faster than measured.",
  "hint.rtt": "Check the path for congestion or unexpected routing.",

  "anomaly.duplicate_ip": "Duplicate IP / VIP on two nodes",
  "anomaly.duplicate_mac": "Duplicate MAC",
  "anomaly.subnet_on_multiple_vlans": "One subnet on several VLANs",
  "anomaly.no_carrier": "Interface without link",
  "anomaly.new_mac": "New MAC in the network",

  "cell.icmp": "ICMP",
  "cell.tcp": "TCP",
  "cell.mtu": "MTU",
  "cell.path": "path",
  "detail.ping": "ping",
  "detail.echo": "TCP echo",
  "detail.tcp1": "TCP, 1 stream",
  "detail.tcpn": "TCP, {n} streams",
  "detail.udp": "UDP",
  "detail.bidir": "bidirectional",
  "detail.cpu": "CPU local / peer",
  "detail.counters": "counters confirm the interface",
  "detail.counters_bad": "counters do not match",
  "detail.loss": "loss",
  "detail.jitter": "jitter",

  "map.layers": "Layers",
  "map.layer.physical": "Physical and segments",
  "map.layer.paths": "Paths",
  "map.layer.services": "Services",
  "map.only_problems": "Only problems",
  "map.segment": "Segment",
  "map.all": "all",
  "map.export_png": "PNG",
  "map.export_svg": "SVG",
  "map.wall": "Wall mode",
  "map.relayout": "Re-layout",
  "map.hypotheses": "Bottleneck hypotheses",
  "map.remeasure": "Measure again",

  "dev.agents": "Agents",
  "dev.interfaces": "Interfaces",
  "dev.ipam": "IPAM",
  "dev.online": "online",
  "dev.offline": "offline",
  "dev.lite": "lite",
  "dev.kind": "type",
  "dev.speed": "speed",
  "dev.used": "used",
  "dev.free": "free",
  "dev.pool": "DHCP pool",
  "dev.resources": "Resources",
  "dev.routes": "Routes",
  "dev.rules": "Rules",
  "dev.neighbors": "Neighbours",
  "dev.uptime": "uptime",
  "dev.memory": "memory",
  "dev.disks": "disks",
  "dev.env": "environment",

  "runs.title": "Runs",
  "runs.kind": "Kind",
  "runs.status": "Status",
  "runs.started": "Started",
  "runs.duration": "Duration",
  "runs.open": "Open",

  "set.general": "General",
  "set.agents": "Agents",
  "set.users": "Users",
  "set.tokens": "API tokens",
  "set.schedules": "Schedules",
  "set.segments": "Segments",
  "set.audit": "Audit log",
  "set.save": "Save",
  "set.saved": "Saved",
  "set.delete": "Delete",
  "set.add": "Add",
  "set.name": "Name",
  "set.role": "Role",
  "set.created": "Created",
  "set.last_used": "Last used",
  "set.duration_ms": "Test duration, ms",
  "set.streams": "Parallel streams",
  "set.ping_count": "Ping packets",
  "set.rtt_warn": "RTT warning threshold, ms",
  "set.mini_token": "Token for Lanscape Mini agents (port 47701)",
  "set.webhooks": "Webhooks (one URL per line)",
  "set.public_url": "Public URL of the panel (links in notifications)",
  "set.retention": "Keep runs, days",
  "set.add_node": "Add node",
  "set.reusable": "Reusable token",
  "set.expires": "Expires in, hours (0 = never)",
  "set.token_once": "Copy the token now, it is shown only once:",
  "set.install_for": "Install command",
  "set.reg_tokens": "Registration tokens",
  "set.uses": "uses",
  "set.spec": "Schedule",
  "set.spec_hint": "every 5m, hourly or daily 02:00",
  "set.enabled": "enabled",
  "set.expected_mbps": "Expected, Mbit/s (0 = from link speed)",
  "set.confirm_delete": "Delete {name}?",
  "set.password": "Password",
  "set.disabled": "disabled",

  "acc.password": "Change password",
  "acc.old": "Current password",
  "acc.new": "New password",
  "acc.totp": "Two-factor authentication",
  "acc.totp_on": "enabled",
  "acc.totp_off": "disabled",
  "acc.totp_enable": "Enable",
  "acc.totp_disable": "Disable",
  "acc.totp_scan": "Add this key to your authenticator app, then enter the current code:",
  "acc.confirm": "Confirm",

  "common.loading": "Loading…",
  "common.error": "Error",
  "common.close": "Close",
  "common.copy": "Copy",
  "common.copied": "Copied",
  "common.yes": "yes",
  "common.no": "no",
  "common.search": "Search",
  "common.offline_data": "Offline: showing the last saved data",
  "nav.dashboard": "Dashboard",
  "nav.services": "Services",
  "nav.monitors": "Monitors",
  "nav.changes": "Changes",
  "dash.empty": "No services on the dashboard yet. Review the found services or add one manually.",
  "dash.found_new": "{n} new services found",
  "dash.review": "Review",
  "dash.up": "up",
  "dash.degraded": "degraded",
  "dash.down": "down",
  "dash.incidents": "Open incidents",
  "dash.no_incidents": "No open incidents",
  "dash.network": "Network",
  "dash.network_none": "No network check yet",
  "dash.paths": "{n} paths",
  "dash.resources": "Nodes",
  "dash.certs": "Certificates expiring",
  "dash.no_certs": "Nothing expires in 30 days",
  "dash.changes": "Recent changes",
  "dash.maintenance": "Maintenance: {name} until {until}",
  "dash.ungrouped": "Services",
  "dash.days_left": "{n} d",
  "dash.updates": "{n} updates",
  "svc.catalog": "Catalog",
  "svc.found": "Found",
  "svc.rescan": "Rescan",
  "svc.rescan_done": "Asked {n} agents",
  "svc.add": "Add",
  "svc.add_manual": "Add service",
  "svc.ignore": "Ignore",
  "svc.hide": "Hide",
  "svc.restore": "Restore",
  "svc.with_monitor": "create monitor",
  "svc.with_tile": "show on dashboard",
  "svc.show": "Show",
  "svc.status_new": "new",
  "svc.status_added": "added",
  "svc.status_ignored": "ignored",
  "svc.status_hidden": "hidden",
  "svc.gone": "gone",
  "svc.no_found": "Nothing found yet. Agents report listening ports, containers and Kubernetes objects every few minutes.",
  "svc.no_services": "No services yet.",
  "svc.internal_url": "Internal URL",
  "svc.external_url": "External URL",
  "svc.group": "Group",
  "svc.tile": "Dashboard tile",
  "svc.notes": "Notes",
  "svc.addresses": "Addresses",
  "svc.recommended": "Recommended check",
  "svc.rule": "rule “{name}”",
  "svc.edit": "Edit",
  "svc.open": "Open",
  "svc.delete_monitors": "also delete its monitors",
  "svc.sources": "found via",
  "mon.monitors": "Monitors",
  "mon.incidents": "Incidents",
  "mon.maintenance": "Maintenance",
  "mon.new": "New monitor",
  "mon.none": "No monitors yet.",
  "mon.type": "Type",
  "mon.target": "Target",
  "mon.target_hint_http": "https://host/path",
  "mon.target_hint_hostport": "host:port",
  "mon.target_hint_host": "host name or IP",
  "mon.interval": "Interval, s",
  "mon.retries": "Failures before incident",
  "mon.points": "Check from",
  "mon.server": "server",
  "mon.min_failing": "Incident when failing from at least",
  "mon.points_n": "points",
  "mon.keyword": "Keyword",
  "mon.regex": "regex",
  "mon.invert": "must be absent",
  "mon.expect_status": "Expected status codes",
  "mon.expect_status_hint": "e.g. 200, 2 (any 2xx); empty = 200–399",
  "mon.json_path": "JSON path",
  "mon.json_value": "JSON value",
  "mon.ignore_tls": "ignore TLS errors",
  "mon.no_redirects": "do not follow redirects",
  "mon.send": "Send",
  "mon.expect": "Expect in answer",
  "mon.dns_server": "DNS server",
  "mon.record": "Record",
  "mon.warn_days": "Warn before expiry, days",
  "mon.service": "Service",
  "mon.no_service": "— none —",
  "mon.test": "Test",
  "mon.check_now": "Check now",
  "mon.pause": "Pause",
  "mon.resume": "Resume",
  "mon.uptime": "Uptime",
  "mon.day": "24 h",
  "mon.week": "7 days",
  "mon.month": "30 days",
  "mon.year": "1 year",
  "mon.response": "Response time",
  "mon.history": "90 days",
  "mon.last_check": "Last check {when}",
  "mon.cert": "Certificate valid until {date}",
  "mon.status.pending": "pending",
  "mon.status.up": "up",
  "mon.status.degraded": "degraded",
  "mon.status.down": "down",
  "mon.status.paused": "paused",
  "mon.status.maintenance": "maintenance",
  "mon.status.unknown": "unknown",
  "inc.opened": "opened {when}",
  "inc.closed": "resolved after {d}",
  "inc.ongoing": "ongoing for {d}",
  "inc.ack": "Acknowledge",
  "inc.acked": "acknowledged by {user}",
  "inc.note": "Comment",
  "inc.add_note": "Add comment",
  "inc.none": "No incidents in the last 30 days.",
  "inc.in_maintenance": "during maintenance",
  "mnt.now": "Right now for",
  "mnt.minutes": "minutes",
  "mnt.planned": "Planned",
  "mnt.starts": "Starts",
  "mnt.ends": "Ends",
  "mnt.all": "all monitors",
  "mnt.none": "No maintenance windows.",
  "mnt.create": "Create",
  "mnt.active": "active",
  "chg.none": "No changes yet.",
  "chg.more": "Load more",
  "chg.service_new": "New service",
  "chg.port_opened": "Port opened",
  "chg.port_closed": "Port closed",
  "chg.container_gone": "Container disappeared",
  "chg.container_stopped": "Container stopped",
  "chg.container_started": "Container started",
  "chg.ip_changed": "IP changed",
  "chg.object_new": "New object",
  "chg.object_gone": "Object removed",
  "chg.device_new": "New device",
  "chg.mac_new": "New MAC address",
  "set.notifications": "Notifications",
  "set.discovery": "Discovery",
  "ch.type": "Channel",
  "ch.test": "Send test",
  "ch.sent": "Test notification sent",
  "ch.none": "No channels. Incidents are shown in the panel only.",
  "ch.bot_token": "Bot token",
  "ch.chat_id": "Chat ID",
  "ch.url": "URL",
  "ch.secret": "Signing secret (optional)",
  "ch.host": "SMTP server",
  "ch.port": "Port",
  "ch.username": "User",
  "ch.password": "Password",
  "ch.from": "From",
  "ch.to": "To (comma-separated)",
  "ch.tls": "Encryption",
  "ch.topic": "Topic",
  "ch.token": "Access token (optional)",
  "ch.server_url": "Server",
  "ch.quiet": "Quiet hours (e.g. 22:00-07:00)",
  "ch.repeat": "Repeat until acknowledged, minutes (0 = off)",
  "ch.no_resolved": "do not send “resolved”",
  "rule.none": "No rules: everything found waits in the queue.",
  "rule.kind": "Found as",
  "rule.any": "any",
  "rule.app": "Application (glob, * = any recognised)",
  "rule.category": "Category",
  "rule.tls_only": "TLS only",
  "rule.action": "Action",
  "rule.add": "add",
  "rule.ignore": "ignore",
  "rule.hint": "Rules apply to newly found services, first match wins.",
  "pal.placeholder": "Search services, devices, IP, MAC…",
  "pal.hint": "Ctrl+K",
  "pal.nothing": "Nothing found",
  "pal.action.check_all": "Check the whole network",
  "pal.action.rescan": "Rescan services",
  "pal.action.maintenance": "Maintenance for 30 minutes",
  "pal.action.new_monitor": "New monitor",
  "pal.type.service": "service",
  "pal.type.monitor": "monitor",
  "pal.type.agent": "agent",
  "pal.type.device": "device",
  "pal.type.found": "found",
  "pal.type.action": "action",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.all": "all",
  "mon.type.http": "HTTP(S)",
  "mon.type.tcp": "TCP",
  "mon.type.udp": "UDP",
  "mon.type.icmp": "Ping (ICMP)",
  "mon.type.dns": "DNS",
  "mon.type.tls": "TLS certificate",
  "mon.type.domain": "Domain expiry",
  "mon.type.heartbeat": "Heartbeat (push)",
  "mon.type.composite": "Composite",
  "mon.heartbeat_hint": "An external job (cron, backup script) calls the push URL shown after saving; silence longer than the interval plus grace opens an incident.",
  "mon.grace": "Grace, s",
  "mon.expr": "Up when (monitor ids)",
  "mon.parents": "Depends on (incidents are suppressed while a parent is down)",
  "mon.push_url": "Push URL",
  "inc.suppressed": "caused by a parent failure",
  "dash.dependents": "+{n} dependent",
  "mon.type.container": "Docker container",
  "mon.type.k8s": "Kubernetes workload",
  "mon.type.vm": "VM / CT",
  "mon.target_hint_resource": "source:agent:key, e.g. proxmox:*:qemu/100 (added from Found)",
  "map.history": "Path history",
  "ch.app_token": "Application token",
  "ch.priority": "Priority",
  "ch.webhook_url": "Webhook URL",
  "ch.homeserver": "Homeserver",
  "ch.access_token": "Access token",
  "ch.room_id": "Room ID",
  "set.status": "Status pages",
  "st.slug": "Address (slug)",
  "st.title": "Title",
  "st.public": "public",
  "st.link_only": "by link only",
  "st.description": "Description",
  "st.domain": "Custom domain",
  "st.accent": "Accent colour",
  "st.logo": "Logo URL",
  "st.theme": "Theme",
  "st.add_group": "Add group",
  "st.none": "No status pages yet.",
  "dev.discovered": "Discovered",
  "dev.vendor": "vendor",
  "dev.sources": "found via",
  "dev.none_discovered": "No devices discovered yet: agents report ARP neighbours, mDNS and SSDP announcements.",
} as const;

export type Key = keyof typeof en;

export const ru: Record<Key, string> = {
  "app.name": "Lanscape",
  "nav.network": "Сеть",
  "nav.map": "Карта",
  "nav.devices": "Устройства",
  "nav.runs": "Прогоны",
  "nav.settings": "Настройки",
  "nav.account": "Аккаунт",
  "nav.logout": "Выйти",
  "theme.toggle": "Сменить тему",
  "lang.toggle": "English",

  "login.title": "Вход",
  "login.username": "Имя пользователя",
  "login.password": "Пароль",
  "login.code": "Код 2FA",
  "login.submit": "Войти",
  "setup.title": "Создайте администратора",
  "setup.hint": "Пользователей ещё нет. Первая учётная запись станет администратором.",
  "setup.submit": "Создать и войти",
  "setup.password_hint": "Не короче 10 символов",

  "net.check_all": "Проверить всё",
  "net.reachability": "Только доступность",
  "net.aggregate": "Aggregate",
  "net.cancel": "Отмена",
  "net.options": "Параметры",
  "net.udp": "UDP-тест",
  "net.bidir": "В обе стороны одновременно",
  "net.duration": "Длительность, с",
  "net.streams": "Потоков",
  "net.estimate": "{paths} путей, примерно {time}",
  "net.running": "Идёт прогон: {done} из {total}, осталось ~{eta}",
  "net.last_run": "Последний прогон #{id}, {when}",
  "net.no_run": "Прогонов ещё не было. Нажмите «Проверить всё».",
  "net.no_agents": "Подключите хотя бы два агента с общей сетью (Настройки → Агенты).",
  "net.problems": "Проблемы",
  "net.no_problems": "Проблем не найдено.",
  "net.matrix": "Матрица скоростей",
  "net.from_to": "откуда \\ куда",
  "net.expected": "ожидается {v}",
  "net.unknown": "неизвестно",
  "net.anomalies": "Аномалии",
  "net.aggregate_result": "Суммарная ёмкость",
  "net.total": "всего",

  "verdict.green": "≥ 85% ожидаемого",
  "verdict.yellow": "50–85% ожидаемого",
  "verdict.red": "< 50% или ошибка",
  "verdict.purple": "упёрлось в CPU агента",
  "verdict.none": "нет ожидаемой скорости / данных",

  "problem.tcp_intercepted": "TCP перехвачен при рабочем ICMP",
  "problem.mtu": "Проблема MTU",
  "problem.slow": "Скорость ниже ожидаемой",
  "problem.path_mismatch": "Путь не совпадает",
  "problem.unreachable": "Недоступен",
  "problem.macvlan": "macvlan-родитель не видит ребёнка",
  "problem.loss": "Потери пакетов",
  "problem.cpu_bound": "Ограничено CPU",
  "problem.rtt": "Высокая задержка",
  "hint.tcp_intercepted":
    "Прозрачный прокси (TPROXY/REDIRECT) или файрвол перехватывает TCP в этой подсети. Исключите подсеть из перехвата.",
  "hint.mtu": "На пути есть линк с меньшим MTU. Выровняйте MTU на всех участках или уменьшите его на концах.",
  "hint.slow": "Проверьте согласование скорости, кабели и аплинки между коммутаторами.",
  "hint.path_mismatch": "Трафик ушёл через другой интерфейс. Проверьте маршруты, ip rule и rp_filter.",
  "hint.unreachable": "Проверьте тегирование VLAN, файрвол и что агент слушает порт 47700.",
  "hint.macvlan":
    "Создайте на хосте macvlan-брата (ip link add storage0 link <parent> type macvlan mode bridge) и перенесите адрес хоста на него.",
  "hint.loss": "Проверьте кабели, дуплекс и ошибки интерфейса.",
  "hint.cpu_bound": "CPU агента был загружен полностью; линк может быть быстрее измеренного.",
  "hint.rtt": "Проверьте путь на перегрузку или неожиданную маршрутизацию.",

  "anomaly.duplicate_ip": "Дубль IP / VIP на двух узлах",
  "anomaly.duplicate_mac": "Дубль MAC",
  "anomaly.subnet_on_multiple_vlans": "Одна подсеть на разных VLAN",
  "anomaly.no_carrier": "Интерфейс без линка",
  "anomaly.new_mac": "Новый MAC в сети",

  "cell.icmp": "ICMP",
  "cell.tcp": "TCP",
  "cell.mtu": "MTU",
  "cell.path": "путь",
  "detail.ping": "ping",
  "detail.echo": "TCP-эхо",
  "detail.tcp1": "TCP, 1 поток",
  "detail.tcpn": "TCP, потоков: {n}",
  "detail.udp": "UDP",
  "detail.bidir": "в обе стороны",
  "detail.cpu": "CPU свой / пира",
  "detail.counters": "счётчики подтверждают интерфейс",
  "detail.counters_bad": "счётчики не совпадают",
  "detail.loss": "потери",
  "detail.jitter": "джиттер",

  "map.layers": "Слои",
  "map.layer.physical": "Физика и сегменты",
  "map.layer.paths": "Пути",
  "map.layer.services": "Сервисы",
  "map.only_problems": "Только проблемы",
  "map.segment": "Сегмент",
  "map.all": "все",
  "map.export_png": "PNG",
  "map.export_svg": "SVG",
  "map.wall": "На стену",
  "map.relayout": "Перераскладка",
  "map.hypotheses": "Гипотезы узких мест",
  "map.remeasure": "Перемерить",

  "dev.agents": "Агенты",
  "dev.interfaces": "Интерфейсы",
  "dev.ipam": "IPAM",
  "dev.online": "в сети",
  "dev.offline": "не в сети",
  "dev.lite": "lite",
  "dev.kind": "тип",
  "dev.speed": "скорость",
  "dev.used": "занято",
  "dev.free": "свободно",
  "dev.pool": "пул DHCP",
  "dev.resources": "Ресурсы",
  "dev.routes": "Маршруты",
  "dev.rules": "Правила",
  "dev.neighbors": "Соседи",
  "dev.uptime": "аптайм",
  "dev.memory": "память",
  "dev.disks": "диски",
  "dev.env": "окружение",

  "runs.title": "Прогоны",
  "runs.kind": "Вид",
  "runs.status": "Статус",
  "runs.started": "Начат",
  "runs.duration": "Длительность",
  "runs.open": "Открыть",

  "set.general": "Общие",
  "set.agents": "Агенты",
  "set.users": "Пользователи",
  "set.tokens": "API-токены",
  "set.schedules": "Расписания",
  "set.segments": "Сегменты",
  "set.audit": "Журнал аудита",
  "set.save": "Сохранить",
  "set.saved": "Сохранено",
  "set.delete": "Удалить",
  "set.add": "Добавить",
  "set.name": "Название",
  "set.role": "Роль",
  "set.created": "Создан",
  "set.last_used": "Использован",
  "set.duration_ms": "Длительность теста, мс",
  "set.streams": "Параллельных потоков",
  "set.ping_count": "Пакетов ping",
  "set.rtt_warn": "Порог RTT, мс",
  "set.mini_token": "Токен для агентов Lanscape Mini (порт 47701)",
  "set.webhooks": "Webhooks (по одному URL в строке)",
  "set.public_url": "Публичный адрес панели (ссылки в уведомлениях)",
  "set.retention": "Хранить прогоны, дней",
  "set.add_node": "Добавить узел",
  "set.reusable": "Многоразовый токен",
  "set.expires": "Срок действия, часов (0 — бессрочно)",
  "set.token_once": "Скопируйте токен сейчас, он показывается один раз:",
  "set.install_for": "Команда установки",
  "set.reg_tokens": "Токены регистрации",
  "set.uses": "использований",
  "set.spec": "Расписание",
  "set.spec_hint": "every 5m, hourly или daily 02:00",
  "set.enabled": "включено",
  "set.expected_mbps": "Ожидаемая, Мбит/с (0 — по скорости линка)",
  "set.confirm_delete": "Удалить {name}?",
  "set.password": "Пароль",
  "set.disabled": "отключён",

  "acc.password": "Сменить пароль",
  "acc.old": "Текущий пароль",
  "acc.new": "Новый пароль",
  "acc.totp": "Двухфакторная аутентификация",
  "acc.totp_on": "включена",
  "acc.totp_off": "выключена",
  "acc.totp_enable": "Включить",
  "acc.totp_disable": "Выключить",
  "acc.totp_scan": "Добавьте ключ в приложение-аутентификатор и введите текущий код:",
  "acc.confirm": "Подтвердить",

  "common.loading": "Загрузка…",
  "common.error": "Ошибка",
  "common.close": "Закрыть",
  "common.copy": "Копировать",
  "common.copied": "Скопировано",
  "common.yes": "да",
  "common.no": "нет",
  "common.search": "Поиск",
  "common.offline_data": "Нет связи: показаны последние сохранённые данные",
  "nav.dashboard": "Дашборд",
  "nav.services": "Сервисы",
  "nav.monitors": "Мониторы",
  "nav.changes": "Изменения",
  "dash.empty": "На дашборде пока нет сервисов. Разберите найденные или добавьте вручную.",
  "dash.found_new": "Найдено новых сервисов: {n}",
  "dash.review": "Разобрать",
  "dash.up": "работают",
  "dash.degraded": "с замечаниями",
  "dash.down": "недоступны",
  "dash.incidents": "Открытые инциденты",
  "dash.no_incidents": "Открытых инцидентов нет",
  "dash.network": "Сеть",
  "dash.network_none": "Сеть ещё не проверялась",
  "dash.paths": "путей: {n}",
  "dash.resources": "Узлы",
  "dash.certs": "Истекающие сертификаты",
  "dash.no_certs": "За 30 дней ничего не истекает",
  "dash.changes": "Последние изменения",
  "dash.maintenance": "Обслуживание: {name} до {until}",
  "dash.ungrouped": "Сервисы",
  "dash.days_left": "{n} дн.",
  "dash.updates": "обновлений: {n}",
  "svc.catalog": "Каталог",
  "svc.found": "Найдено",
  "svc.rescan": "Пересканировать",
  "svc.rescan_done": "Запрошено агентов: {n}",
  "svc.add": "Добавить",
  "svc.add_manual": "Добавить сервис",
  "svc.ignore": "Игнорировать",
  "svc.hide": "Скрыть",
  "svc.restore": "Вернуть",
  "svc.with_monitor": "создать монитор",
  "svc.with_tile": "на дашборд",
  "svc.show": "Показать",
  "svc.status_new": "новые",
  "svc.status_added": "добавленные",
  "svc.status_ignored": "игнорируемые",
  "svc.status_hidden": "скрытые",
  "svc.gone": "пропал",
  "svc.no_found": "Пока ничего не найдено. Агенты сообщают о портах, контейнерах и объектах Kubernetes раз в несколько минут.",
  "svc.no_services": "Сервисов пока нет.",
  "svc.internal_url": "Внутренний адрес",
  "svc.external_url": "Внешний адрес",
  "svc.group": "Группа",
  "svc.tile": "Плитка на дашборде",
  "svc.notes": "Заметки",
  "svc.addresses": "Адреса",
  "svc.recommended": "Рекомендуемая проверка",
  "svc.rule": "правило «{name}»",
  "svc.edit": "Изменить",
  "svc.open": "Открыть",
  "svc.delete_monitors": "удалить и мониторы",
  "svc.sources": "найдено через",
  "mon.monitors": "Мониторы",
  "mon.incidents": "Инциденты",
  "mon.maintenance": "Обслуживание",
  "mon.new": "Новый монитор",
  "mon.none": "Мониторов пока нет.",
  "mon.type": "Тип",
  "mon.target": "Цель",
  "mon.target_hint_http": "https://host/path",
  "mon.target_hint_hostport": "host:port",
  "mon.target_hint_host": "имя или IP",
  "mon.interval": "Интервал, с",
  "mon.retries": "Неудач до инцидента",
  "mon.points": "Проверять с",
  "mon.server": "сервер",
  "mon.min_failing": "Инцидент, если недоступен минимум с",
  "mon.points_n": "точек",
  "mon.keyword": "Ключевое слово",
  "mon.regex": "regex",
  "mon.invert": "должно отсутствовать",
  "mon.expect_status": "Ожидаемые коды",
  "mon.expect_status_hint": "например 200, 2 (любой 2xx); пусто = 200–399",
  "mon.json_path": "JSON-путь",
  "mon.json_value": "Значение JSON",
  "mon.ignore_tls": "игнорировать ошибки TLS",
  "mon.no_redirects": "не следовать редиректам",
  "mon.send": "Отправить",
  "mon.expect": "Ожидать в ответе",
  "mon.dns_server": "DNS-сервер",
  "mon.record": "Запись",
  "mon.warn_days": "Предупреждать до истечения, дней",
  "mon.service": "Сервис",
  "mon.no_service": "— нет —",
  "mon.test": "Проверить",
  "mon.check_now": "Проверить сейчас",
  "mon.pause": "Пауза",
  "mon.resume": "Возобновить",
  "mon.uptime": "Доступность",
  "mon.day": "24 ч",
  "mon.week": "7 дней",
  "mon.month": "30 дней",
  "mon.year": "1 год",
  "mon.response": "Время ответа",
  "mon.history": "90 дней",
  "mon.last_check": "Последняя проверка {when}",
  "mon.cert": "Сертификат действует до {date}",
  "mon.status.pending": "ожидание",
  "mon.status.up": "работает",
  "mon.status.degraded": "с замечаниями",
  "mon.status.down": "недоступен",
  "mon.status.paused": "на паузе",
  "mon.status.maintenance": "обслуживание",
  "mon.status.unknown": "неизвестно",
  "inc.opened": "открыт {when}",
  "inc.closed": "закрыт через {d}",
  "inc.ongoing": "длится {d}",
  "inc.ack": "Подтвердить",
  "inc.acked": "подтвердил {user}",
  "inc.note": "Комментарий",
  "inc.add_note": "Добавить комментарий",
  "inc.none": "За 30 дней инцидентов не было.",
  "inc.in_maintenance": "во время обслуживания",
  "mnt.now": "Прямо сейчас на",
  "mnt.minutes": "минут",
  "mnt.planned": "Плановое",
  "mnt.starts": "Начало",
  "mnt.ends": "Конец",
  "mnt.all": "все мониторы",
  "mnt.none": "Окон обслуживания нет.",
  "mnt.create": "Создать",
  "mnt.active": "идёт",
  "chg.none": "Изменений пока нет.",
  "chg.more": "Показать ещё",
  "chg.service_new": "Новый сервис",
  "chg.port_opened": "Открылся порт",
  "chg.port_closed": "Закрылся порт",
  "chg.container_gone": "Контейнер пропал",
  "chg.container_stopped": "Контейнер остановлен",
  "chg.container_started": "Контейнер запущен",
  "chg.ip_changed": "Сменился IP",
  "chg.object_new": "Новый объект",
  "chg.object_gone": "Объект удалён",
  "chg.device_new": "Новое устройство",
  "chg.mac_new": "Новый MAC-адрес",
  "set.notifications": "Уведомления",
  "set.discovery": "Обнаружение",
  "ch.type": "Канал",
  "ch.test": "Отправить тест",
  "ch.sent": "Тестовое уведомление отправлено",
  "ch.none": "Каналов нет. Инциденты видны только в панели.",
  "ch.bot_token": "Токен бота",
  "ch.chat_id": "ID чата",
  "ch.url": "URL",
  "ch.secret": "Секрет подписи (необязательно)",
  "ch.host": "SMTP-сервер",
  "ch.port": "Порт",
  "ch.username": "Пользователь",
  "ch.password": "Пароль",
  "ch.from": "От кого",
  "ch.to": "Кому (через запятую)",
  "ch.tls": "Шифрование",
  "ch.topic": "Топик",
  "ch.token": "Токен доступа (необязательно)",
  "ch.server_url": "Сервер",
  "ch.quiet": "Тихие часы (например 22:00-07:00)",
  "ch.repeat": "Повторять до подтверждения, минут (0 = нет)",
  "ch.no_resolved": "не присылать «восстановлено»",
  "rule.none": "Правил нет: всё найденное ждёт в очереди.",
  "rule.kind": "Найдено как",
  "rule.any": "любое",
  "rule.app": "Приложение (glob, * = любое распознанное)",
  "rule.category": "Категория",
  "rule.tls_only": "только с TLS",
  "rule.action": "Действие",
  "rule.add": "добавить",
  "rule.ignore": "игнорировать",
  "rule.hint": "Правила применяются к новым найденным сервисам, срабатывает первое подходящее.",
  "pal.placeholder": "Поиск сервисов, устройств, IP, MAC…",
  "pal.hint": "Ctrl+K",
  "pal.nothing": "Ничего не найдено",
  "pal.action.check_all": "Проверить всю сеть",
  "pal.action.rescan": "Пересканировать сервисы",
  "pal.action.maintenance": "Обслуживание на 30 минут",
  "pal.action.new_monitor": "Новый монитор",
  "pal.type.service": "сервис",
  "pal.type.monitor": "монитор",
  "pal.type.agent": "агент",
  "pal.type.device": "устройство",
  "pal.type.found": "найдено",
  "pal.type.action": "действие",
  "common.cancel": "Отмена",
  "common.save": "Сохранить",
  "common.delete": "Удалить",
  "common.edit": "Изменить",
  "common.all": "все",
  "mon.type.http": "HTTP(S)",
  "mon.type.tcp": "TCP",
  "mon.type.udp": "UDP",
  "mon.type.icmp": "Ping (ICMP)",
  "mon.type.dns": "DNS",
  "mon.type.tls": "TLS-сертификат",
  "mon.type.domain": "Срок домена",
  "mon.type.heartbeat": "Heartbeat (push)",
  "mon.type.composite": "Составной",
  "mon.heartbeat_hint": "Внешняя задача (cron, скрипт бэкапа) вызывает push-адрес, который появится после сохранения; тишина дольше интервала с запасом открывает инцидент.",
  "mon.grace": "Запас, с",
  "mon.expr": "Работает, если (id мониторов)",
  "mon.parents": "Зависит от (инциденты подавляются, пока родитель недоступен)",
  "mon.push_url": "Push-адрес",
  "inc.suppressed": "из-за сбоя родителя",
  "dash.dependents": "+{n} зависимых",
  "mon.type.container": "Контейнер Docker",
  "mon.type.k8s": "Workload Kubernetes",
  "mon.type.vm": "VM / CT",
  "mon.target_hint_resource": "источник:агент:ключ, например proxmox:*:qemu/100 (из «Найдено»)",
  "map.history": "История пути",
  "ch.app_token": "Токен приложения",
  "ch.priority": "Приоритет",
  "ch.webhook_url": "URL вебхука",
  "ch.homeserver": "Homeserver",
  "ch.access_token": "Токен доступа",
  "ch.room_id": "ID комнаты",
  "set.status": "Страницы статуса",
  "st.slug": "Адрес (slug)",
  "st.title": "Заголовок",
  "st.public": "публичная",
  "st.link_only": "только по ссылке",
  "st.description": "Описание",
  "st.domain": "Свой домен",
  "st.accent": "Цвет акцента",
  "st.logo": "URL логотипа",
  "st.theme": "Тема",
  "st.add_group": "Добавить группу",
  "st.none": "Страниц статуса пока нет.",
  "dev.discovered": "Обнаруженные",
  "dev.vendor": "производитель",
  "dev.sources": "найдено через",
  "dev.none_discovered": "Устройства ещё не найдены: агенты сообщают соседей ARP, объявления mDNS и SSDP.",
};

export type Lang = "en" | "ru";

export function translate(lang: Lang, key: string, params?: Record<string, string | number>): string {
  const dict: Record<string, string> = lang === "ru" ? ru : en;
  let s = dict[key] ?? (en as Record<string, string>)[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) s = s.replaceAll(`{${k}}`, String(v));
  }
  return s;
}
