// UI strings. Every key must exist in both languages (checked by dict.test.ts).

export const en = {
  "app.name": "Lanscape",
  "nav.network": "Network",
  "nav.map": "Map",
  "nav.devices": "Devices",
  "nav.runs": "Runs",
  "nav.settings": "Settings",
  "nav.account": "Account",
  "nav.logout": "Log out",
  "theme.toggle": "Toggle theme",
  "lang.toggle": "Русский",

  "login.title": "Sign in",
  "login.username": "Username",
  "login.password": "Password",
  "login.code": "Two-factor code",
  "login.submit": "Sign in",
  "setup.title": "Create the administrator",
  "setup.hint": "No users exist yet. The first account becomes an administrator.",
  "setup.submit": "Create and sign in",
  "setup.password_hint": "At least 10 characters",

  "net.check_all": "Check all",
  "net.reachability": "Reachability only",
  "net.aggregate": "Aggregate",
  "net.cancel": "Cancel",
  "net.options": "Options",
  "net.udp": "UDP test",
  "net.bidir": "Bidirectional",
  "net.duration": "Duration, s",
  "net.streams": "Streams",
  "net.estimate": "{paths} paths, about {time}",
  "net.running": "Running: {done} of {total}, ~{eta} left",
  "net.last_run": "Last run #{id}, {when}",
  "net.no_run": "No runs yet. Press “Check all”.",
  "net.no_agents": "Connect at least two agents that share a network (Settings → Agents).",
  "net.problems": "Problems",
  "net.no_problems": "No problems found.",
  "net.matrix": "Speed matrix",
  "net.from_to": "from \\ to",
  "net.expected": "expected {v}",
  "net.unknown": "unknown",
  "net.anomalies": "Anomalies",
  "net.aggregate_result": "Aggregate capacity",
  "net.total": "total",

  "verdict.green": "≥ 85% of expected",
  "verdict.yellow": "50–85% of expected",
  "verdict.red": "< 50% or error",
  "verdict.purple": "limited by agent CPU",
  "verdict.none": "no expected speed / no data",

  "problem.tcp_intercepted": "TCP intercepted while ICMP ok",
  "problem.mtu": "MTU problem",
  "problem.slow": "Speed below expected",
  "problem.path_mismatch": "Path does not match",
  "problem.unreachable": "Unreachable",
  "problem.macvlan": "macvlan parent cannot reach child",
  "problem.loss": "Packet loss",
  "problem.cpu_bound": "Limited by CPU",
  "problem.rtt": "High latency",
  "hint.tcp_intercepted":
    "A transparent proxy (TPROXY/REDIRECT) or a firewall captures TCP in this subnet. Exclude the subnet from interception.",
  "hint.mtu": "A link on this path has a smaller MTU. Align the MTU on all hops or lower it on the endpoints.",
  "hint.slow": "Check link negotiation, cabling and the uplinks between switches.",
  "hint.path_mismatch": "Traffic left through another interface. Check routes, ip rule and rp_filter.",
  "hint.unreachable": "Check VLAN tagging, the firewall and that the agent listens on port 47700.",
  "hint.macvlan":
    "Create a macvlan sibling on the host (ip link add storage0 link <parent> type macvlan mode bridge) and move the host address there.",
  "hint.loss": "Check cabling, duplex and interface errors.",
  "hint.cpu_bound": "The agent CPU was saturated; the link may be faster than measured.",
  "hint.rtt": "Check the path for congestion or unexpected routing.",

  "anomaly.duplicate_ip": "Duplicate IP / VIP on two nodes",
  "anomaly.duplicate_mac": "Duplicate MAC",
  "anomaly.subnet_on_multiple_vlans": "One subnet on several VLANs",
  "anomaly.no_carrier": "Interface without link",
  "anomaly.new_mac": "New MAC in the network",

  "cell.icmp": "ICMP",
  "cell.tcp": "TCP",
  "cell.mtu": "MTU",
  "cell.path": "path",
  "detail.ping": "ping",
  "detail.echo": "TCP echo",
  "detail.tcp1": "TCP, 1 stream",
  "detail.tcpn": "TCP, {n} streams",
  "detail.udp": "UDP",
  "detail.bidir": "bidirectional",
  "detail.cpu": "CPU local / peer",
  "detail.counters": "counters confirm the interface",
  "detail.counters_bad": "counters do not match",
  "detail.loss": "loss",
  "detail.jitter": "jitter",

  "map.layers": "Layers",
  "map.layer.physical": "Physical and segments",
  "map.layer.paths": "Paths",
  "map.layer.services": "Services",
  "map.only_problems": "Only problems",
  "map.segment": "Segment",
  "map.all": "all",
  "map.export_png": "PNG",
  "map.export_svg": "SVG",
  "map.wall": "Wall mode",
  "map.relayout": "Re-layout",
  "map.hypotheses": "Bottleneck hypotheses",
  "map.remeasure": "Measure again",

  "dev.agents": "Agents",
  "dev.interfaces": "Interfaces",
  "dev.ipam": "IPAM",
  "dev.online": "online",
  "dev.offline": "offline",
  "dev.lite": "lite",
  "dev.kind": "type",
  "dev.speed": "speed",
  "dev.used": "used",
  "dev.free": "free",
  "dev.pool": "DHCP pool",
  "dev.resources": "Resources",
  "dev.routes": "Routes",
  "dev.rules": "Rules",
  "dev.neighbors": "Neighbours",
  "dev.uptime": "uptime",
  "dev.memory": "memory",
  "dev.disks": "disks",
  "dev.env": "environment",

  "runs.title": "Runs",
  "runs.kind": "Kind",
  "runs.status": "Status",
  "runs.started": "Started",
  "runs.duration": "Duration",
  "runs.open": "Open",

  "set.general": "General",
  "set.agents": "Agents",
  "set.users": "Users",
  "set.tokens": "API tokens",
  "set.schedules": "Schedules",
  "set.segments": "Segments",
  "set.audit": "Audit log",
  "set.save": "Save",
  "set.saved": "Saved",
  "set.delete": "Delete",
  "set.add": "Add",
  "set.name": "Name",
  "set.role": "Role",
  "set.created": "Created",
  "set.last_used": "Last used",
  "set.duration_ms": "Test duration, ms",
  "set.streams": "Parallel streams",
  "set.ping_count": "Ping packets",
  "set.rtt_warn": "RTT warning threshold, ms",
  "set.mini_token": "Token for Lanscape Mini agents (port 47701)",
  "set.webhooks": "Webhooks (one URL per line)",
  "set.retention": "Keep runs, days",
  "set.add_node": "Add node",
  "set.reusable": "Reusable token",
  "set.expires": "Expires in, hours (0 = never)",
  "set.token_once": "Copy the token now, it is shown only once:",
  "set.install_for": "Install command",
  "set.reg_tokens": "Registration tokens",
  "set.uses": "uses",
  "set.spec": "Schedule",
  "set.spec_hint": "every 5m, hourly or daily 02:00",
  "set.enabled": "enabled",
  "set.expected_mbps": "Expected, Mbit/s (0 = from link speed)",
  "set.confirm_delete": "Delete {name}?",
  "set.password": "Password",
  "set.disabled": "disabled",

  "acc.password": "Change password",
  "acc.old": "Current password",
  "acc.new": "New password",
  "acc.totp": "Two-factor authentication",
  "acc.totp_on": "enabled",
  "acc.totp_off": "disabled",
  "acc.totp_enable": "Enable",
  "acc.totp_disable": "Disable",
  "acc.totp_scan": "Add this key to your authenticator app, then enter the current code:",
  "acc.confirm": "Confirm",

  "common.loading": "Loading…",
  "common.error": "Error",
  "common.close": "Close",
  "common.copy": "Copy",
  "common.copied": "Copied",
  "common.yes": "yes",
  "common.no": "no",
  "common.search": "Search",
  "common.offline_data": "Offline: showing the last saved data",
} as const;

export type Key = keyof typeof en;

export const ru: Record<Key, string> = {
  "app.name": "Lanscape",
  "nav.network": "Сеть",
  "nav.map": "Карта",
  "nav.devices": "Устройства",
  "nav.runs": "Прогоны",
  "nav.settings": "Настройки",
  "nav.account": "Аккаунт",
  "nav.logout": "Выйти",
  "theme.toggle": "Сменить тему",
  "lang.toggle": "English",

  "login.title": "Вход",
  "login.username": "Имя пользователя",
  "login.password": "Пароль",
  "login.code": "Код 2FA",
  "login.submit": "Войти",
  "setup.title": "Создайте администратора",
  "setup.hint": "Пользователей ещё нет. Первая учётная запись станет администратором.",
  "setup.submit": "Создать и войти",
  "setup.password_hint": "Не короче 10 символов",

  "net.check_all": "Проверить всё",
  "net.reachability": "Только доступность",
  "net.aggregate": "Aggregate",
  "net.cancel": "Отмена",
  "net.options": "Параметры",
  "net.udp": "UDP-тест",
  "net.bidir": "В обе стороны одновременно",
  "net.duration": "Длительность, с",
  "net.streams": "Потоков",
  "net.estimate": "{paths} путей, примерно {time}",
  "net.running": "Идёт прогон: {done} из {total}, осталось ~{eta}",
  "net.last_run": "Последний прогон #{id}, {when}",
  "net.no_run": "Прогонов ещё не было. Нажмите «Проверить всё».",
  "net.no_agents": "Подключите хотя бы два агента с общей сетью (Настройки → Агенты).",
  "net.problems": "Проблемы",
  "net.no_problems": "Проблем не найдено.",
  "net.matrix": "Матрица скоростей",
  "net.from_to": "откуда \\ куда",
  "net.expected": "ожидается {v}",
  "net.unknown": "неизвестно",
  "net.anomalies": "Аномалии",
  "net.aggregate_result": "Суммарная ёмкость",
  "net.total": "всего",

  "verdict.green": "≥ 85% ожидаемого",
  "verdict.yellow": "50–85% ожидаемого",
  "verdict.red": "< 50% или ошибка",
  "verdict.purple": "упёрлось в CPU агента",
  "verdict.none": "нет ожидаемой скорости / данных",

  "problem.tcp_intercepted": "TCP перехвачен при рабочем ICMP",
  "problem.mtu": "Проблема MTU",
  "problem.slow": "Скорость ниже ожидаемой",
  "problem.path_mismatch": "Путь не совпадает",
  "problem.unreachable": "Недоступен",
  "problem.macvlan": "macvlan-родитель не видит ребёнка",
  "problem.loss": "Потери пакетов",
  "problem.cpu_bound": "Ограничено CPU",
  "problem.rtt": "Высокая задержка",
  "hint.tcp_intercepted":
    "Прозрачный прокси (TPROXY/REDIRECT) или файрвол перехватывает TCP в этой подсети. Исключите подсеть из перехвата.",
  "hint.mtu": "На пути есть линк с меньшим MTU. Выровняйте MTU на всех участках или уменьшите его на концах.",
  "hint.slow": "Проверьте согласование скорости, кабели и аплинки между коммутаторами.",
  "hint.path_mismatch": "Трафик ушёл через другой интерфейс. Проверьте маршруты, ip rule и rp_filter.",
  "hint.unreachable": "Проверьте тегирование VLAN, файрвол и что агент слушает порт 47700.",
  "hint.macvlan":
    "Создайте на хосте macvlan-брата (ip link add storage0 link <parent> type macvlan mode bridge) и перенесите адрес хоста на него.",
  "hint.loss": "Проверьте кабели, дуплекс и ошибки интерфейса.",
  "hint.cpu_bound": "CPU агента был загружен полностью; линк может быть быстрее измеренного.",
  "hint.rtt": "Проверьте путь на перегрузку или неожиданную маршрутизацию.",

  "anomaly.duplicate_ip": "Дубль IP / VIP на двух узлах",
  "anomaly.duplicate_mac": "Дубль MAC",
  "anomaly.subnet_on_multiple_vlans": "Одна подсеть на разных VLAN",
  "anomaly.no_carrier": "Интерфейс без линка",
  "anomaly.new_mac": "Новый MAC в сети",

  "cell.icmp": "ICMP",
  "cell.tcp": "TCP",
  "cell.mtu": "MTU",
  "cell.path": "путь",
  "detail.ping": "ping",
  "detail.echo": "TCP-эхо",
  "detail.tcp1": "TCP, 1 поток",
  "detail.tcpn": "TCP, потоков: {n}",
  "detail.udp": "UDP",
  "detail.bidir": "в обе стороны",
  "detail.cpu": "CPU свой / пира",
  "detail.counters": "счётчики подтверждают интерфейс",
  "detail.counters_bad": "счётчики не совпадают",
  "detail.loss": "потери",
  "detail.jitter": "джиттер",

  "map.layers": "Слои",
  "map.layer.physical": "Физика и сегменты",
  "map.layer.paths": "Пути",
  "map.layer.services": "Сервисы",
  "map.only_problems": "Только проблемы",
  "map.segment": "Сегмент",
  "map.all": "все",
  "map.export_png": "PNG",
  "map.export_svg": "SVG",
  "map.wall": "На стену",
  "map.relayout": "Перераскладка",
  "map.hypotheses": "Гипотезы узких мест",
  "map.remeasure": "Перемерить",

  "dev.agents": "Агенты",
  "dev.interfaces": "Интерфейсы",
  "dev.ipam": "IPAM",
  "dev.online": "в сети",
  "dev.offline": "не в сети",
  "dev.lite": "lite",
  "dev.kind": "тип",
  "dev.speed": "скорость",
  "dev.used": "занято",
  "dev.free": "свободно",
  "dev.pool": "пул DHCP",
  "dev.resources": "Ресурсы",
  "dev.routes": "Маршруты",
  "dev.rules": "Правила",
  "dev.neighbors": "Соседи",
  "dev.uptime": "аптайм",
  "dev.memory": "память",
  "dev.disks": "диски",
  "dev.env": "окружение",

  "runs.title": "Прогоны",
  "runs.kind": "Вид",
  "runs.status": "Статус",
  "runs.started": "Начат",
  "runs.duration": "Длительность",
  "runs.open": "Открыть",

  "set.general": "Общие",
  "set.agents": "Агенты",
  "set.users": "Пользователи",
  "set.tokens": "API-токены",
  "set.schedules": "Расписания",
  "set.segments": "Сегменты",
  "set.audit": "Журнал аудита",
  "set.save": "Сохранить",
  "set.saved": "Сохранено",
  "set.delete": "Удалить",
  "set.add": "Добавить",
  "set.name": "Название",
  "set.role": "Роль",
  "set.created": "Создан",
  "set.last_used": "Использован",
  "set.duration_ms": "Длительность теста, мс",
  "set.streams": "Параллельных потоков",
  "set.ping_count": "Пакетов ping",
  "set.rtt_warn": "Порог RTT, мс",
  "set.mini_token": "Токен для агентов Lanscape Mini (порт 47701)",
  "set.webhooks": "Webhooks (по одному URL в строке)",
  "set.retention": "Хранить прогоны, дней",
  "set.add_node": "Добавить узел",
  "set.reusable": "Многоразовый токен",
  "set.expires": "Срок действия, часов (0 — бессрочно)",
  "set.token_once": "Скопируйте токен сейчас, он показывается один раз:",
  "set.install_for": "Команда установки",
  "set.reg_tokens": "Токены регистрации",
  "set.uses": "использований",
  "set.spec": "Расписание",
  "set.spec_hint": "every 5m, hourly или daily 02:00",
  "set.enabled": "включено",
  "set.expected_mbps": "Ожидаемая, Мбит/с (0 — по скорости линка)",
  "set.confirm_delete": "Удалить {name}?",
  "set.password": "Пароль",
  "set.disabled": "отключён",

  "acc.password": "Сменить пароль",
  "acc.old": "Текущий пароль",
  "acc.new": "Новый пароль",
  "acc.totp": "Двухфакторная аутентификация",
  "acc.totp_on": "включена",
  "acc.totp_off": "выключена",
  "acc.totp_enable": "Включить",
  "acc.totp_disable": "Выключить",
  "acc.totp_scan": "Добавьте ключ в приложение-аутентификатор и введите текущий код:",
  "acc.confirm": "Подтвердить",

  "common.loading": "Загрузка…",
  "common.error": "Ошибка",
  "common.close": "Закрыть",
  "common.copy": "Копировать",
  "common.copied": "Скопировано",
  "common.yes": "да",
  "common.no": "нет",
  "common.search": "Поиск",
  "common.offline_data": "Нет связи: показаны последние сохранённые данные",
};

export type Lang = "en" | "ru";

export function translate(lang: Lang, key: string, params?: Record<string, string | number>): string {
  const dict: Record<string, string> = lang === "ru" ? ru : en;
  let s = dict[key] ?? (en as Record<string, string>)[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) s = s.replaceAll(`{${k}}`, String(v));
  }
  return s;
}
