/* Converts a binary file into a C array: bin2c <input> <name> > out.h */
#include <stdio.h>

int main(int argc, char **argv)
{
    FILE *f;
    int c;
    unsigned long n = 0;
    if (argc != 3) {
        fprintf(stderr, "usage: bin2c <input> <name>\n");
        return 2;
    }
    f = fopen(argv[1], "rb");
    if (!f) {
        perror(argv[1]);
        return 1;
    }
    printf("/* generated by mini/tools/bin2c from %s; do not edit */\n", argv[1]);
    printf("static const unsigned char %s[] = {", argv[2]);
    while ((c = fgetc(f)) != EOF) {
        printf("%s0x%02x,", n % 16 ? "" : "\n    ", c);
        n++;
    }
    printf("\n};\n");
    fclose(f);
    return 0;
}
